schema:
  - "http://localhost:3000/graphql" 
documents:
  - "src/**/*.gql" 
generates:
  ./generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
